### ISSUE TITLE
verify email endpoint

### ISSUE THREAD

**Issue by solace** [perak/kitchen-site#106] opened 2015-06-08 14:06 UTC
Hi,

The examples provide usage for setting up the login, register, forgot and reset password endpoints. Does it also support email verification and enrollment functionality?

**Comment by perak** [comment] 2015-06-08 19:59
Hi,

Sorry, e-mail verification is not yet supported.

**Comment by solace** [comment] 2015-06-09 14:20
Workaround:

1. In `public_zone.pages`, add a page to the effect of:

    ```
{ "name": "verify_email", "custom_template": "templates/verify_email", "route_params": ["verificationToken"], "zoneless: true }
```

    One thing that is unclear is that `zoneless` is applied to a page after it has been added to an `application` level zone. May I ask why this is an attribute as opposed to a zone separate to `free_`, `public_` or `private_`?

2. Add corresponding  `.html` and `.js` pages for the custom template.  The html template can be empty, the js can be derived from https://gentlenode.com/journal/meteor-20-verify-an-email-with-meteor-accounts/42

    The following example stays on the `/verify_email` page, but `Router.go('/');` can be added to redirect back to the homepage inside the `verifyEmail` callback and the no token clause. You can also augment this with an alerts package.
    ```
    Template.VerifyEmail.created = function() {
        var verificationToken = Router.current().params.verificationToken;
        if (verificationToken) {
            Accounts.verifyEmail(verificationToken, function (err) {
                if (err) {
                    if (err.message === 'Verify email link expired [403]') {
                        console.log('verification link has expired.');
                    }
                    else {
                        console.log(err.message);
                    }
                }
                else {
                    console.log('email address has been confirmed.');
                }
            });
        }
        else {
            console.log('no verification token provided.');
        }
    };
```

3. In `server_startup` code or source file, add the following to change the generated URL for this accounts endpoint:

    ```
        Accounts.urls.verifyEmail = function (token) {
            return Meteor.absoluteUrl('verify_email/' + token);
        };
    ```

**Comment by Billybobbonnet** [comment] 2015-06-09 15:01
nice! thank you @solace :smiley:

**Comment by perak** [comment] 2015-06-25 22:02
@solace thank you!

"Verify e-mail" functionality is now added and will be available in next version (0.9.43).

@solace @Billybobbonnet  About `zoneless` - since version 0.9.42, application with user accounts can have all three zones: public, private and free (it was not possible before). "photosharing" example is updated and demonstrates how to add pages into free zone and make it accessible for both authenticated and non-authenticated users.

`zoneless` property will be removed in near future.

**Comment by perak** [comment] 2015-07-02 08:37
I am closing this issue (fixed in 0.9.43). 
If you still find issues related to e-mail verification, feel free to reopen it.

**Closed by perak** 2015-07-02 08:37 UTC

**Comment by a4xrbj1** [comment] 2015-11-02 13:10
@perak @solace Can we re-open this issue? I'm using version 0.9.54 and even though the app said that the verification email is being send I never received it (checked my spam folder as well). Did I miss something that needs to be set in order to get this to work?

**Comment by perak** [comment] 2015-11-02 13:19
@a4xrbj1 are you doing it in your localhost? If so, e-mail is not sent indeed - it's only printed to your server console (so you can copy & paste e-mail verification URL from terminal). This is for testing only.

If you upload (deploy) your application using `meteor deploy ...` command, e-mails will be actually sent (meteor hosting sets it up automatically for you).

If you deploy your application to 3rd party service (VPS?) then you are responsible to set proper environment variables and setup e-mail server.

**Comment by perak** [comment] 2015-11-02 13:22
BTW, this is how Meteor works - not related to meteor-kitchen. Anyway, above explanation can be useful to other users in the future.

**Comment by a4xrbj1** [comment] 2015-11-02 13:22
Thanks @perak - I couldn't find this in the documentation (Getting started) or the API reference at all. It would be nice if this hint is added there (next to some basic information about this feature).

**Comment by a4xrbj1** [comment] 2015-11-02 13:26
You're correct, all the detailed email information is in the terminal. However, when I copy the URL and paste it into my browser I get a "Page not found". Both for the URL with the token as well as for http://localhost:3000/verify_email/

**Comment by perak** [comment] 2015-11-02 13:28
Well... it is in Meteor docs: http://docs.meteor.com/#/full/email

> If MAIL_URL is not set (eg, when running your application locally), Email.send outputs the message to standard output instead.

But, I believe you are using meteor-kitchen to learn Meteor, and maybe I should make my docs in that way (current docs are actually opposite - assumed is that meteor-kitchen user is highly familiar with meteor and uses meteor-kitchen to bootstrap/prototype app...).

**Comment by perak** [comment] 2015-11-02 13:32
Please paste here what you copied and pasted to your browser.

URL usually looks something like this:

```
http://localhost:3000/verify_email/d0SRIQziQXMgKntxWH6HTaoEfMA24rOyVPwQXTFmmAw
```

**Comment by a4xrbj1** [comment] 2015-11-02 13:36
http://localhost:3000/verify_email/2LWnxS-nIlKO-_REFrYS4ElJveA4Y-KJs0BoMOZKvX2

**Comment by perak** [comment] 2015-11-02 13:39
And... it doesn't work? Saying "page not found?". Hum... strange. Maybe I'm asking stupid questions, but: is meteor still running (you didn't stopped it in terminal?).

**Comment by a4xrbj1** [comment] 2015-11-02 13:42
Yes, it was still running. The "page not found" was actually displayed in the body of the page

**Comment by perak** [comment] 2015-11-02 23:34
@a4xrbj1 ah... I understand now. you need to add "verify e-mail" page to your application.

In the same place where are your login and register pages, you need to add page with following attributes:

```
{ 
  "name": "verify_email",
  "template": "verify_email",
  "route_params": ["verifyEmailToken"]
}
```

That's it. :)

**Comment by perak** [comment] 2015-11-02 23:41
Ooops - I found a bug - it cannot be done from gui - it doesn't show `verify_email` in `template: ` dropdown. 

Fixed and will be available in next meteor-kitchen version.

Until then, what you can do is to go to "Edit source" page, and paste this code (for example, after your "register" page:

```
				{
					"name": "verify_email",
					"template": "verify_email",
					"route_params": [
						"verifyEmailToken"
					],
					"type": "page"
				},
```

**Comment by Rob-McCormack** [comment] 2016-02-24 14:51
Thanks for the fix... 

I placed this code in my .json file,

```example-accounts.json```

 and it created the new page and correct routes

 I can confirm it worked.  Much appreciated.  I'll do more testing on production site today.

~ Rob
