### ISSUE TITLE
There is no route for the path: /

### ISSUE THREAD

**Issue by mukulhase** [perak/kitchen-site#387] opened 2017-09-24 06:25 UTC
On building the following app:
`meteor-kitchen https://www.meteorkitchen.com/api/getapp/json/KSpEkWKDmzmcJMpTk seller-hub`
And running, it reports 
![screenshot from 2017-09-24 11-54-47](https://user-images.githubusercontent.com/9693405/30780035-3457b9c0-a11f-11e7-995d-6cd110696087.png)

**Comment by perak** [comment] 2017-09-24 06:57
This usually happens when there is an error while executing meteor-kitchen. Please copy & paste output from terminal (or command prompt).

**Comment by mukulhase** [comment] 2017-09-24 09:13
Output
Created a new Meteor app in 'seller-hub/'.

To run your new app:
  cd seller-hub/
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials


Changes to your project's package version selections:

blaze-tools            removed from your project
caching-compiler       removed from your project
caching-html-compiler  removed from your project
deps                   removed from your project
html-tools             removed from your project
htmljs                 removed from your project
spacebars-compiler     removed from your project
static-html            removed from your project
templating-tools       removed from your project

static-html: removed dependency

Changes to your project's package version selections:

accounts-base                added, version 1.3.3
accounts-password            added, version 1.4.0
blaze                        added, version 2.3.2
blaze-html-templates         added, version 1.1.2
blaze-tools                  added, version 1.0.10
caching-compiler             added, version 1.1.9
caching-html-compiler        added, version 1.1.2
ddp-rate-limiter             added, version 1.0.7
deps                         added, version 1.0.12
email                        added, version 1.2.3
fortawesome:fontawesome      added, version 4.7.0
html-tools                   added, version 1.0.11
htmljs                       added, version 1.0.11
jquery                       added, version 1.11.10
kadira:flow-router           added, version 2.12.1
less                         added, version 2.7.9
localstorage                 added, version 1.1.1
matb33:collection-hooks      added, version 0.8.4
meteorhacks:picker           added, version 1.0.3
npm-bcrypt                   added, version 0.9.3
observe-sequence             added, version 1.0.16
perak:joins                  added, version 1.1.6
rate-limit                   added, version 1.0.8
react-meteor-data            added, version 0.2.13
reactive-dict                added, version 1.1.9
service-configuration        added, version 1.0.11
session                      added, version 1.1.7
sha                          added, version 1.0.9
spacebars                    added, version 1.0.15
spacebars-compiler           added, version 1.1.3
spiderable                   added, version 1.0.13
srp                          added, version 1.0.10
templating                   added, version 1.3.2
templating-compiler          added, version 1.3.3
templating-runtime           added, version 1.3.2
templating-tools             added, version 1.1.2
tmeasday:check-npm-versions  added, version 0.2.0
twbs:bootstrap               added, version 3.3.6
ui                           added, version 1.0.13


accounts-password: Password support for accounts
perak:joins: Generic collection joins for Meteor
blaze-html-templates: Compile HTML templates into reactive UI with Meteor Blaze
kadira:flow-router: Carefully Designed Client Side Router for Meteor
react-meteor-data: React higher-order component for reactively tracking Meteor
data
reactive-dict: Reactive dictionary
meteorhacks:picker: Server Side Router for Meteor
check: Check whether a value matches a pattern
random: Random number generator and utilities
accounts-base: A user account system
http: Make HTTP calls to remote servers
email: Send email messages
spiderable: Makes the application crawlable to web spiders
ejson: Extended and Extensible JSON library
session: Session variable
fortawesome:fontawesome: Font Awesome (official): 500+ scalable vector icons,
customizable via CSS, Retina friendly
matb33:collection-hooks: Extends Mongo.Collection with before/after hooks for
insert/update/remove/find/findOne
less: Leaner CSS language
twbs:bootstrap: The most popular front-end framework for developing responsive,
mobile first projects on the web.

> bcrypt@1.0.3 install /home/mukul/Documents/github/test/seller-hub/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/home/mukul/Documents/github/test/seller-hub/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
seller-hub@ /home/mukul/Documents/github/test/seller-hub
+-- bcrypt@1.0.3 
| +-- nan@2.6.2 
| `-- node-pre-gyp@0.6.36 
|   +-- mkdirp@0.5.1 
|   | `-- minimist@0.0.8 
|   +-- nopt@4.0.1 
|   | +-- abbrev@1.1.0 
|   | `-- osenv@0.1.4 
|   |   +-- os-homedir@1.0.2 
|   |   `-- os-tmpdir@1.0.2 
|   +-- npmlog@4.1.2 
|   | +-- are-we-there-yet@1.1.4 
|   | | +-- delegates@1.0.0 
|   | | `-- readable-stream@2.3.3  deduped
|   | +-- console-control-strings@1.1.0 
|   | +-- gauge@2.7.4 
|   | | +-- aproba@1.2.0 
|   | | +-- console-control-strings@1.1.0  deduped
|   | | +-- has-unicode@2.0.1 
|   | | +-- object-assign@4.1.1  deduped
|   | | +-- signal-exit@3.0.2 
|   | | +-- string-width@1.0.2 
|   | | | +-- code-point-at@1.1.0 
|   | | | +-- is-fullwidth-code-point@1.0.0 
|   | | | | `-- number-is-nan@1.0.1 
|   | | | `-- strip-ansi@3.0.1  deduped
|   | | +-- strip-ansi@3.0.1 
|   | | | `-- ansi-regex@2.1.1 
|   | | `-- wide-align@1.1.2 
|   | |   `-- string-width@1.0.2  deduped
|   | `-- set-blocking@2.0.0 
|   +-- rc@1.2.1 
|   | +-- deep-extend@0.4.2 
|   | +-- ini@1.3.4 
|   | +-- minimist@1.2.0 
|   | `-- strip-json-comments@2.0.1 
|   +-- request@2.82.0 
|   | +-- aws-sign2@0.7.0 
|   | +-- aws4@1.6.0 
|   | +-- caseless@0.12.0 
|   | +-- combined-stream@1.0.5 
|   | | `-- delayed-stream@1.0.0 
|   | +-- extend@3.0.1 
|   | +-- forever-agent@0.6.1 
|   | +-- form-data@2.3.1 
|   | | +-- asynckit@0.4.0 
|   | | +-- combined-stream@1.0.5  deduped
|   | | `-- mime-types@2.1.17  deduped
|   | +-- har-validator@5.0.3 
|   | | +-- ajv@5.2.2 
|   | | | +-- co@4.6.0 
|   | | | +-- fast-deep-equal@1.0.0 
|   | | | +-- json-schema-traverse@0.3.1 
|   | | | `-- json-stable-stringify@1.0.1 
|   | | |   `-- jsonify@0.0.0 
|   | | `-- har-schema@2.0.0 
|   | +-- hawk@6.0.2 
|   | | +-- boom@4.3.1 
|   | | | `-- hoek@4.2.0  deduped
|   | | +-- cryptiles@3.1.2 
|   | | | `-- boom@5.2.0 
|   | | |   `-- hoek@4.2.0  deduped
|   | | +-- hoek@4.2.0 
|   | | `-- sntp@2.0.2 
|   | |   `-- hoek@4.2.0  deduped
|   | +-- http-signature@1.2.0 
|   | | +-- assert-plus@1.0.0 
|   | | +-- jsprim@1.4.1 
|   | | | +-- assert-plus@1.0.0  deduped
|   | | | +-- extsprintf@1.3.0 
|   | | | +-- json-schema@0.2.3 
|   | | | `-- verror@1.10.0 
|   | | |   +-- assert-plus@1.0.0  deduped
|   | | |   +-- core-util-is@1.0.2  deduped
|   | | |   `-- extsprintf@1.3.0  deduped
|   | | `-- sshpk@1.13.1 
|   | |   +-- asn1@0.2.3 
|   | |   +-- assert-plus@1.0.0  deduped
|   | |   +-- bcrypt-pbkdf@1.0.1 
|   | |   | `-- tweetnacl@0.14.5  deduped
|   | |   +-- dashdash@1.14.1 
|   | |   | `-- assert-plus@1.0.0  deduped
|   | |   +-- ecc-jsbn@0.1.1 
|   | |   | `-- jsbn@0.1.1  deduped
|   | |   +-- getpass@0.1.7 
|   | |   | `-- assert-plus@1.0.0  deduped
|   | |   +-- jsbn@0.1.1 
|   | |   `-- tweetnacl@0.14.5 
|   | +-- is-typedarray@1.0.0 
|   | +-- isstream@0.1.2 
|   | +-- json-stringify-safe@5.0.1 
|   | +-- mime-types@2.1.17 
|   | | `-- mime-db@1.30.0 
|   | +-- oauth-sign@0.8.2 
|   | +-- performance-now@2.1.0 
|   | +-- qs@6.5.1 
|   | +-- safe-buffer@5.1.1 
|   | +-- stringstream@0.0.5 
|   | +-- tough-cookie@2.3.3 
|   | | `-- punycode@1.4.1 
|   | +-- tunnel-agent@0.6.0 
|   | | `-- safe-buffer@5.1.1  deduped
|   | `-- uuid@3.1.0 
|   +-- rimraf@2.6.2 
|   | `-- glob@7.1.2 
|   |   +-- fs.realpath@1.0.0 
|   |   +-- inflight@1.0.6 
|   |   | +-- once@1.4.0  deduped
|   |   | `-- wrappy@1.0.2  deduped
|   |   +-- inherits@2.0.3  deduped
|   |   +-- minimatch@3.0.4 
|   |   | `-- brace-expansion@1.1.8 
|   |   |   +-- balanced-match@1.0.0 
|   |   |   `-- concat-map@0.0.1 
|   |   +-- once@1.4.0  deduped
|   |   `-- path-is-absolute@1.0.1 
|   +-- semver@5.4.1 
|   +-- tar@2.2.1 
|   | +-- block-stream@0.0.9 
|   | | `-- inherits@2.0.3  deduped
|   | +-- fstream@1.0.11 
|   | | +-- graceful-fs@4.1.11 
|   | | +-- inherits@2.0.3  deduped
|   | | +-- mkdirp@0.5.1  deduped
|   | | `-- rimraf@2.6.2  deduped
|   | `-- inherits@2.0.3 
|   `-- tar-pack@3.4.0 
|     +-- debug@2.6.9 
|     | `-- ms@2.0.0 
|     +-- fstream@1.0.11  deduped
|     +-- fstream-ignore@1.0.5 
|     | +-- fstream@1.0.11  deduped
|     | +-- inherits@2.0.3  deduped
|     | `-- minimatch@3.0.4  deduped
|     +-- once@1.4.0 
|     | `-- wrappy@1.0.2 
|     +-- readable-stream@2.3.3 
|     | +-- core-util-is@1.0.2 
|     | +-- inherits@2.0.3  deduped
|     | +-- isarray@1.0.0 
|     | +-- process-nextick-args@1.0.7 
|     | +-- safe-buffer@5.1.1  deduped
|     | +-- string_decoder@1.0.3 
|     | | `-- safe-buffer@5.1.1  deduped
|     | `-- util-deprecate@1.0.2 
|     +-- rimraf@2.6.2  deduped
|     +-- tar@2.2.1  deduped
|     `-- uid-number@0.0.6 
+-- meteor-user-roles@1.1.1 
+-- moment@2.18.1 
+-- prop-types@15.5.10 
| +-- fbjs@0.8.15 
| | +-- core-js@1.2.7 
| | +-- isomorphic-fetch@2.2.1 
| | | +-- node-fetch@1.7.3 
| | | | +-- encoding@0.1.12 
| | | | | `-- iconv-lite@0.4.19 
| | | | `-- is-stream@1.1.0 
| | | `-- whatwg-fetch@2.0.3 
| | +-- loose-envify@1.3.1  deduped
| | +-- object-assign@4.1.1  deduped
| | +-- promise@7.3.1 
| | | `-- asap@2.0.6 
| | +-- setimmediate@1.0.5 
| | `-- ua-parser-js@0.7.14 
| `-- loose-envify@1.3.1 
|   `-- js-tokens@3.0.2 
+-- react@15.6.1 
| +-- create-react-class@15.6.0 
| | +-- fbjs@0.8.15  deduped
| | +-- loose-envify@1.3.1  deduped
| | `-- object-assign@4.1.1  deduped
| +-- fbjs@0.8.15  deduped
| +-- loose-envify@1.3.1  deduped
| +-- object-assign@4.1.1 
| `-- prop-types@15.5.10  deduped
+-- react-addons-pure-render-mixin@15.6.0 
| +-- fbjs@0.8.15  deduped
| `-- object-assign@4.1.1  deduped
+-- react-dom@15.6.1 
| +-- fbjs@0.8.15  deduped
| +-- loose-envify@1.3.1  deduped
| +-- object-assign@4.1.1  deduped
| `-- prop-types@15.5.10  deduped
`-- react-mounter@1.2.0 
  `-- domready@1.0.8 


*** Meteor Kitchen v0.9.84 ***
Source code generator for Meteor.js - www.meteorkitchen.com
Copyright (c) Petar Korponaić
<petar.korponaic@gmail.com>

Downloading input file...
Reading input file... 
Executing "meteor create seller-hub/ --bare"...
Creating directory structure...
Checking installed packages...
Executing "meteor remove static-html"...
Checking installed packages...
Executing "meteor add accounts-password perak:joins blaze-html-templates kadira:flow-router react-meteor-data reactive-dict meteorhacks:picker check random accounts-base http email spiderable ejson session fortawesome:fontawesome matb33:collection-hooks less twbs:bootstrap"...
Executing "meteor npm install --save  react react-dom react-mounter react-addons-pure-render-mixin prop-types bcrypt meteor-user-roles moment"...
Executing "meteor npm install"...
Creating router...
Using theme "bootswatch-paper"...
Copying theme files...
Creating stylesheet...
Creating layout...
Creating zone "public_zone"...
Creating component "left_menu"...
Creating component "right_menu"...
Creating page "home_public"...
Creating component "home_jumbotron"...
Creating component "listings"...
Creating page "login"...
Creating page "register"...
Creating page "verify_email"...
Creating page "forgot_password"...
Creating page "reset_password"...
Creating zone "private_zone"...
Creating component "left_menu"...
Creating component "right_menu"...
Creating page "home_private"...
Creating page "admin"...
Creating component "side_menu"...
Creating page "users"...
Creating component "view"...
Creating page "details"...
Creating component "details_form"...
Creating page "insert"...
Creating component "insert_form"...
Creating page "edit"...
Creating component "edit_form"...
Creating page "user_settings"...
Creating component "side_menu"...
Creating page "profile"...
Creating component "edit_form"...
Creating page "change_pass"...
Creating page "logout"...
Creating page "sellers_hub"...
Creating component "tabs"...
Creating page "individual_sellers_hub"...
Creating collection "achievements"...
Creating collection "chats"...
Creating collection "sellers"...
Creating collection "items"...

Collection "items" references non-existing role "blocked". Please add this role to application.roles array.
`

`

**Comment by perak** [comment] 2017-09-24 10:45
OK, so meteor-kitchen stopped with error, and this is related to "blocked" role. Might be a bug in meteor-kitchen itself, or possibly wrong settings in your project. I'll check what is the cause when I reach my computer.

**Comment by perak** [comment] 2017-10-03 11:14
Fixed in `v0.9.87`

**Closed** 2018-09-10 21:13 UTC
