### ISSUE TITLE
Generator generates only one insert_form instead of two and crashes 

### ISSUE THREAD

**Issue by RemKolomna** [perak/kitchen-site#102] opened 2015-06-04 14:32 UTC
PS: Platform: Windows7 64 bit, ver v0.9.39 
if regenerate project into the same folder it crashes on generating customers collection
{
	"application": {
		"title": "iPawn",
		"meta_title": "iPawn",
		"meta_description": "iPawn",
		"theme": "bootswatch-flatly",

		"roles": [ "admin", "manager", "blocked" ],
		"default_role": "admin",

		"use_collection2": false,

		"collections": [
			{
				"name": "photos",
				"type": "file_collection",
				"storage_adapters": ["gridfs"]
			},

			{
				"name": "documentScans",
				"type": "file_collection",
				"storage_adapters": ["gridfs"]
			},

			{
				"name": "catalog",
				"fileds": [
					{ "name": "name" }
				]
			},

			{
				"name": "shops",
				"fileds": [
					{ "name": "name", "title": "Название", "required": true, "exportable": true },
					{ "name": "town", "title": "Город", "required": true, "exportable": true },
					{ "name": "address", "title": "Адрес", "required": true, "exportable": true },
					{ "name": "phone", "title": "Телефон", "required": true, "exportable": true },
					{
						"name": "photo",
						"title": "Фото",
						"input": "file",
						"file_collection": "photos",
						"file_container": "file"
					}
				]
			},

			{
				"name": "customers",
				"fields": [
					{ "name": "lastName", "title": "Фамилия", "required": true, "exportable": true },
          { "name": "firstName", "title": "Имя", "required": true, "exportable": true },
          { "name": "middleName", "title": "Отчество", "required": true, "exportable": true },

          { "name": "birthday", "title": "День рождения", "type": "date", "input": "datepicker", "format": "DD.MM.YYYY", "exportable": true },
          { "name": "settlement", "title": "Населённый пункт", "required": true, "exportable": true },
          { "name": "street", "title": "Улица", "required": true, "exportable": true },
          { "name": "house", "title": "Дом", "required": true, "type": "integer", "exportable": true },
          { "name": "appartment", "title": "Квартира", "type": "integer", "exportable": true },

					{ "name": "document", "title": "Документ", "exportable": true },
					{ "name": "documentNumber", "title": "Номер, серия", "exportable": true },
					{ "name": "documentIssuedBy", "title": "Кем выдан", "exportable": true },
					{ "name": "documentWhenIssued", "title": "Когда выдан", "type": "date", "input": "datepicker", "format": "DD.MM.YYYY", "exportable": true },

					{
						"name": "documentScan",
						"title": "Скан паспорта",
						"input": "file",
						"file_collection": "documentScans",
						"file_container": "file"
					},

					{ "name": "phone", "title": "Телефон", "default": "", "exportable": true },
					{ "name": "note", "title": "Note", "input": "textarea", "exportable": true },
					{ "name": "active", "title": "Active", "type": "bool", "input": "checkbox", "display_helper": "booleanToYesNo", "exportable": true }
				]
			}
		],

		"public_zone": {
			"pages": [
				{
					"name": "home_public",
					"title": "",
					"components": [
						{
							"name": "home_jumbotron",
							"title": "iPawn",
							"type": "jumbotron",
							"text": "Добро пожаловать в систему управления вашим бизнесом",
							"button_title": "Регистрация",
							"button_route": "login"
						}
					]
				},
				{ "name": "login", "title": "Войти", "template": "login" },
				{ "name": "register", "template": "register" },
				{ "name": "forgot_password", "template": "forgot_password" },
				{ "name": "reset_password", "template": "reset_password", "route_params": ["resetPasswordToken"] }
			],

			"menus": [
				{
					"name": "left_menu",
					"class": "nav navbar-nav",
					"dest_selector": "#menu",
					"items": [
						{ "title": "Стартовая страница", "route": "home_public" }
					]
				},

				{
					"name": "right_menu",
					"class": "nav navbar-nav navbar-right",
					"dest_selector": "#menu",
					"items": [
						{ "title": "Регистрация", "route": "register" },
						{ "title": "Войти", "route": "login" }
					]
				}
			]
		},

		"private_zone": {
			"pages": [
				{
					"name": "home_private",
					"title": "",
					"components": [
						{
							"name": "home_jumbotron",
							"title": "iPawn",
							"type": "jumbotron",
							"text": "Добро пожаловать в систему управления",
							"button_title": "Просмотреть клиентов",
							"button_route": "customers"
						}
					]
				},

				{
					"name": "customers",
					"components": [
						{
							"name": "view",
							"type": "data_view",
							"title": "Клиенты",
							"text_if_empty": "У вас ещё нет клиентов",
							"query": {
								"name": "customers",
								"collection": "customers",
								"filter": {}
							},
							"insert_route": "customers.insert",
							"edit_route": "customers.edit",
							"edit_route_params": [
								{ "name": "customerId", "value": "this._id" }
							],
							"details_route": "customers.details",
							"details_route_params": [
								{ "name": "customerId", "value": "this._id" }
							]
						}
					],
					"pages": [
						{
							"name": "insert",
							"components": [
								{
									"name": "insert_form",
									"type": "form",
									"mode": "insert",
									"title": "Новый клиент",
									"query": {
										"name": "customers_empty",
										"collection": "customers",
										"filter": {"_id": null}
									},
									"submit_route": "customers",
									"cancel_route": "customers"
								}
							]
						},
						{
							"name": "details",
							"route_params": ["customerId"],
							"components": [
								{
									"name": "details_form",
									"type": "form",
									"mode": "read_only",
									"title": "Подробности",
									"layout": "horizontal",
									"query": {
										"name": "customer",
										"collection": "customers",
										"filter": { "_id": ":customerId" }
									},
									"close_route": "customers",
									"back_route": "customers"
								}
							]
						},

						{
							"name": "edit",
							"route_params": ["customerId"],
							"components": [
								{
									"name": "edit_form",
									"type": "form",
									"mode": "update",
									"title": "Редактирование клиента",
									"submit_route": "customers",
									"cancel_route": "customers",
									"query": {
										"name": "customer",
										"collection": "customers",
										"filter": { "_id": ":customerId" }
									}
								}
							]
						}
					]
				},

				{
					"name": "shops",
					"components": [
						{
							"name": "view",
							"type": "data_view",
							"title": "Ломбарды",
							"text_if_empty": "Ломбарды отсутствуют",
							"query": {
								"name": "shops",
								"collection": "shops",
								"filter": {}
							},
							"insert_route": "shops.insert",
							"edit_route": "shops.edit",
							"edit_route_params": [
								{ "name": "shopId", "value": "this._id" }
							],
							"details_route": "shops.details",
							"details_route_params": [
								{ "name": "shopId", "value": "this._id" }
							]
						}
					],
					"pages": [
						{
							"name": "insert2",
							"components": [
								{
									"name": "insert_form2",
									"type": "form",
									"mode": "insert",
									"title": "Новый ломбард",
									"query": {
										"name": "shops_empty",
										"collection": "shops",
										"filter": {"_id": null}
									},
									"submit_route": "shops",
									"cancel_route": "shops"
								}
							]
						},
						{
							"name": "details",
							"route_params": ["shopId"],
							"components": [
								{
									"name": "details_form",
									"type": "form",
									"mode": "read_only",
									"title": "Подробности",
									"layout": "horizontal",
									"query": {
										"name": "shop",
										"collection": "shops",
										"filter": { "_id": ":shopId" }
									},
									"close_route": "shops",
									"back_route": "shops"
								}
							]
						},

						{
							"name": "edit",
							"route_params": ["shopId"],
							"components": [
								{
									"name": "edit_form",
									"type": "form",
									"mode": "update",
									"title": "Редактирование ломбарда",
									"submit_route": "shops",
									"cancel_route": "shops",
									"query": {
										"name": "shop",
										"collection": "shops",
										"filter": { "_id": ":shopId" }
									}
								}
							]
						}
					]
				},

				{
					"name": "admin",
					"roles": ["admin"],
					"pages": [
						{
							"name": "users",
							"components": [
								{
									"name": "view",
									"type": "data_view",
									"title": "Пользователи",
									"text_if_empty": "Пользователи отсутствуют",
									"query": {
										"name": "admin_users",
										"collection": "users",
										"filter": {}
									},

									"fields": [
										{ "name": "profile.name", "title": "Name"},
										{ "name": "profile.email", "title": "E-mail" },
										{ "name": "roles", "title": "Role" }
									],

									"insert_route": "admin.users.insert",

									"edit_route": "admin.users.edit",
									"edit_route_params": [
										{ "name": "userId", "value": "this._id" }
									],

									"details_route": "admin.users.details",
									"details_route_params": [
										{ "name": "userId", "value": "this._id" }
									]
								}
							],
							"pages": [
								{
									"name": "details",
									"route_params": ["userId"],
									"components": [
										{
											"name": "details_form",
											"type": "form",
											"mode": "read_only",
											"title": "Данные пользователя",
											"query": {
												"name": "admin_user",
												"collection": "users",
												"filter": { "_id": ":userId" }
											},
											"fields": [
												{ "name": "profile.name", "title": "Name"},
												{ "name": "profile.email", "title": "E-mail", "type": "email" },
												{ "name": "roles", "title": "Role" }
											],
											"close_route": "admin.users",
											"back_route": "admin.users"
										}
									]
								},
								{
									"name": "insert",
									"components": [
										{
											"name": "insert_form",
											"type": "form",
											"mode": "insert",
											"title": "Добавить нового пользователя",
											"submit_route": "admin.users",
											"cancel_route": "admin.users",
											"query": {
												"name": "users_null",
												"collection": "users",
												"filter": { "_id": null }
											},
											"fields": [
												{ "name": "profile.name", "title": "Имя", "required": true },
												{ "name": "profile.email", "title": "Электронная почта", "type": "email", "required": true },
												{ "name": "password", "title": "Пароль", "input": "password", "required": true }
											]
										}
									]
								},
								{
									"name": "edit",
									"route_params": ["userId"],
									"components": [
										{
											"name": "edit_form",
											"type": "form",
											"mode": "update",
											"title": "Редактировать пользователя",
											"submit_route": "admin.users",
											"cancel_route": "admin.users",
											"query": {
												"name": "admin_user",
												"collection": "users",
												"filter": { "_id": ":userId" }
											},
											"fields": [
												{ "name": "profile.name", "title": "Name", "required": true },
												{ "name": "profile.email", "title": "E-mail", "type": "email", "required": true },
												{
													"name": "roles",
													"type": "array",
													"title": "Role",
													"input": "radio",
													"input_items": [
														{ "value": "manager", "title": "Менеджер" },
														{ "value": "admin", "title": "Администратор" },
														{ "value": "blocked", "title": "Заблокирован" }
													]
												}
											]
										}
									]
								}
							]
						}

					],

					"menus": [
						{
							"name": "side_menu",
							"class": "nav nav-stacked nav-pills",
							"items": [
								{ "title": "Пользователи", "route": "admin.users" }
							]
						}
					]
				},

				{
					"name": "user_settings",
					"roles": ["manager", "admin", "blocked"],
					"pages": [
						{
							"name": "profile",
							"components": [
								{
									"name": "edit_form",
									"type": "form",
									"mode": "update",
									"title": "Редактирование вашего профиля",
									"submit_route": "user_settings.profile",
									"query": {
										"name": "current_user_data",
										"collection": "users",
										"filter": { "_id": "Meteor.userId()" },
										"find_one": true
									},
									"fields": [
										{ "name": "profile.name", "title": "Имя", "required": true },
										{ "name": "profile.email", "title": "Электронная почта", "type": "email", "required": true },
										{ "name": "profile.facebook", "title": "Facebook URL" },
										{ "name": "profile.google", "title": "Google+ URL" },
										{ "name": "profile.twitter", "title": "Twitter ID" },
										{ "name": "profile.website", "title": "Website URL" }
									]
								}
							]
						},

						{ "name": "change_pass", "template": "change_pass" }
					],

					"menus": [
						{
							"name": "side_menu",
							"class": "nav nav-stacked nav-pills",
							"items": [
								{ "title": "Profile", "route": "user_settings.profile" },
								{ "title": "Change password", "route": "user_settings.change_pass" }
							]
						}
					]
				},

				{ "name": "logout", "template": "logout", "action_code": "App.logout();" }
			],

			"menus": [
				{
					"name": "left_menu",
					"class": "nav navbar-nav",
					"dest_selector": "#menu",
					"items": [
						{ "title": "Домашняя страница", "route": "home_private" },
						{ "title": "Клиенты",	"route": "customers" },
						{ "title": "Ломбарды",	"route": "shops" }
					]
				},
				{
					"name": "right_menu",
					"class": "nav navbar-nav navbar-right",
					"dest_selector": "#menu",
					"items": [
						{ "title": "Администратор", "route": "admin" },

						{
							"title": "{{userEmail}}",
							"items": [
								{ "title": "Настройки", "route": "user_settings" },
								{ "title": "Выход", "route": "logout" }
							]
						}
					]
				}
			]
		}
	}
}

**Comment by perak** [comment] 2015-06-04 21:11
Hi,

I just built your application, and it builds normally. I did it in linux
(don't have windows on this machine at the moment).

- What is your meteor-kitchen version? (your program works with v0.9.39, at
least under linux, I didn't tested it under windows yet).

- Can you copy-paste error message? (is there any error message?).

By the way, your route "shops.insert" should be "shops.insert2" (because
insert form for shops is named "name": "insert2").


Cheers!
Petar

**Comment by perak** [comment] 2015-06-04 21:16
One more thing: did you try to do "clean" build? (generate fresh app in new
directory)

**Comment by RemKolomna** [comment] 2015-06-05 05:24
Hi, Peter!

I opened meteor kitchen in debugger and get the error: Unhandled exception
at 0x00418347 in meteor-kitchen.exe: 0xC0000005: Access violation reading
location 0x00000000. It looks like dereferencing null pointer in the
generator code

In assembly it looks like this:
00418304  push        eax
00418305  movzx       eax,byte ptr [esp+2Bh]
0041830A  mov         dword ptr [esp+14h],eax
0041830E  movzx       eax,byte ptr [esp+2Ah]
00418313  mov         dword ptr [esp+10h],eax
00418317  movzx       eax,byte ptr [esp+29h]
0041831C  mov         dword ptr [esp+0Ch],eax
00418320  lea         edx,[esp+6Ch]
00418324  mov         dword ptr [esp+8],edx
00418328  movzx       eax,byte ptr [esp+28h]
0041832D  mov         dword ptr [esp+4],eax
00418331  mov         ecx,dword ptr [esp+80h]
00418338  mov         dword ptr [esp],ecx
0041833B  mov         dword ptr [esp+30h],1
00418343  mov         eax,dword ptr [esp+20h]
00418347  mov         ecx,dword ptr [eax]  <--- exception! - looks like a
null pointer is sent as a parameter of some routine

However if i do a fresh build into non-existent folder the error is not
occurred. But I have another problem - insert form of shops collection is
absolutely empty, except "Save" and "Cancel" buttons, I fix route to
shops.insert2, but it didn't help.

Best regards, Roman Kolesnikov

**Comment by perak** [comment] 2015-06-05 10:09
Please help me to reproduce that. Step-by-step instructions to produce that
bug.

Thanks!

**Comment by RemKolomna** [comment] 2015-06-05 11:12
Hi!

Steps are simple

1)first step in console I run command
meteor-kitchen.exe pawn.json app
then in file app\client\views\shops\insert2\insert2.html i can see no input
controls generated

2)if I run the same command again
meteor-kitchen.exe pawn.json app

your program outputs:
*** Meteor Kitchen v0.9.39 ***
Meteor Application Generator - www.meteorkitchen.com
Copyright (c) Petar Korponai─З
<petar.korponaic@gmail.com>

Reading input file...
Checking installed packages...
Creating directory structure...
Creating router...
Creating collection "photos"...
Creating collection "document_scans"...
Creating collection "shops"...
Creating collection "customers"...

and crashes

the file pawn.json is included in attachments

Best regards, Roman Kolesnikov

**Comment by RemKolomna** [comment] 2015-06-06 11:36
Excuse me, Peter!

The problem number one was wrong - the input fields hasn't generated due to
my type in "fields" key.
But the problem two - crash - still persists. The source of problem is in
lines

{
"name": "documentScan",
"title": "Скан паспорта",
"input": "file",
"file_collection": "documentsScans",
"file_container": "file"
}

if I remove this field - everything works ok!

But i found solution of my problem - I moved the description of
documentsScans just  before customers collection and everything works ok!

**Comment by perak** [comment] 2015-06-06 20:12
Sorry for my late answers,  glad to see you fixed the problem, but problem still persists - now I know what's the bug and I'l fix it in next version. Thanks for your patience and bug-catch!

**Comment by RemKolomna** [comment] 2015-06-06 20:54
Thank you for your time and your program! Hope it will be the best!

Best regards, Roman Kolesnikov

**Comment by perak** [comment] 2015-06-06 21:11
Thanks. Yes, it will be the best! :+1: :smile:

**Comment by perak** [comment] 2015-07-02 08:39
I think this issue is fixed. Closing.

**Closed by perak** 2015-07-02 08:39 UTC
