### ISSUE TITLE
Designer UI for query with user collections shows nothing, not collection name

### ISSUE THREAD

**Issue by aaronmyhre** [perak/kitchen-site#118] opened 2015-07-23 18:15 UTC
Using the example:admin project, the image collection is not displayed in "query: admin_users" query. I assume this is due to the "user" collection being included as part of the user management package, rather then a custom defined collection. 

<img width="1119" alt="screen shot 2015-07-23 at 11 09 56 am" src="https://cloud.githubusercontent.com/assets/2838202/8858372/eddf44d2-312b-11e5-9fc5-4fe70421bdf3.png">

**Comment by perak** [comment] 2015-07-24 07:54
@aaronmyhre excuse me for late answer. First to say, GUI is mostly auto generated and not very well implemented, some tasks are hard to be done or even impossible using current GUI. Work on a complete new GUI is in progress. However, let's fix bug you found (if this is a bug) but please try to explaincincmore details - help me reproduce issue. TNX.

**Comment by aaronmyhre** [comment] 2015-07-28 19:23
Hey Perak - 

Thanks for the response and sorry for my late response now. I really appreciate all of the work you have done on meteorkitchen, such a cool application!

These are the steps to reproduce:
1. home -> new -> create new -> initial template = example: Admin
2. browse to query in designer (private.pages.admin.pages.users.components.view.query) (picture)
3. look at JSON for corresponding query in edit source (picture below)

issue: the GUI does not have the user collection selected, whereas it is in the JSON

root cause: I believe the issue is that the users collection is created as part of the user management package, rather then defined in meteor kitchen. Therefore the "users" value is not available in the collections pick list, yet it is defined in the JSON the GUI is based on. 

Pictures:
<img width="1123" alt="screen shot 2015-07-28 at 12 20 04 pm" src="https://cloud.githubusercontent.com/assets/2838202/8941235/500b7f9a-3523-11e5-8608-84bfacd44077.png">
<img width="1046" alt="screen shot 2015-07-28 at 12 20 19 pm" src="https://cloud.githubusercontent.com/assets/2838202/8941236/515b6a22-3523-11e5-92fd-3395606e9a1e.png">


There is another interesting scenario for this issue. When trying to define a join between a custom collection ("foo" for example) and the "users" collection, the users collection is not available from the pick list. I tried to circumvent the GUI by updating the JSON to reference the users collection, however the build failed on the following error "You are trying to join with non-existing collection "users". Creating a "dummy" user collection also does't work as the application fails to start of a duplicate collection error.

**Comment by perak** [comment] 2015-07-28 20:23
Good catch!

OK, uploading new version in few minutes...

**Comment by perak** [comment] 2015-07-28 20:34
OK, fixed and uploaded, but only first part of issue: now you can choose collection name from the list. But, you still cannot join with users collection because generator will report "non-existing" collection. This is also fixed, but will be available in next regulat meteor-kitchen update (version v0.9.48).

Thanks for bugcatch!

**Comment by aaronmyhre** [comment] 2015-07-28 22:33
very cool, thanks! I'm looking forward to 0.9.48 and and an example for joins!

**Comment by perak** [comment] 2015-07-28 22:38
:+1:

**Comment by perak** [comment] 2015-07-28 22:44
P.S. another ugly bug is just solved: any application that contains collection was unable to be built from GUI (but was able to be built with CLI). If you had this problem, solution is:

GUI sets wrong `"type": "string"` to collection objects, correct is `"type": "collection"`.

Example (wrong):
```Json
{
  "name": "customers",
  "type": "string",
  "fields": [ .... ]
}
```

Correct one:
```Json
{
  "name": "customers",
  "type": "collection",
  "fields": [ .... ]
}
```

**Comment by perak** [comment] 2015-08-10 23:20
Should be fixed now (v0.9.48 is just uploaded)

**Comment by aaronmyhre** [comment] 2015-08-11 00:11
woot!

**Comment by perak** [comment] 2015-10-14 09:08
I think this issue is fixed, closing...

**Closed by perak** 2015-10-14 09:08 UTC
