### ISSUE TITLE
File upload does not work when fields are specified in competent. 

### ISSUE THREAD

**Issue by aaronmyhre** [perak/kitchen-site#121] opened 2015-08-02 05:01 UTC
Issue: When a component that has a query for a collection that contains a reference to a file_collection, the "file upload" input will not "automagically" appear in the UI when fields are specified for that component. 

Example:
This will have the file upload UI created:

"components": [
	{
		"name": "insert_form",
		"title": "add new gift",
		"mode": "insert",
		"submit_route": "admin.gifts",
		"cancel_route": "admin.gifts",
		"type": "form",
		"query": {
			"name": "gifts_null",
			"collection": "Gifts",
			"find_one": false,
			"filter": {
				"_id": null
			},
			"options": {},
			"params": []
		}
	}
] 

This will not have the file upload UI created 

"components": [
	{
		"name": "insert_form",
		"title": "add new gift",
		"mode": "insert",
		"submit_route": "admin.gifts",
		"cancel_route": "admin.gifts",
		"type": "form",
		"query": {
			"name": "gifts_null",
			"collection": "Gifts",
			"find_one": false,
			"filter": {
				"_id": null
			},
			"options": {},
			"params": []
		},
		"fields": [
			{
				"name": "title",
				"title": "title",
				"type": "string"
			}
		]
	}
]

I know the documentation says that the file upload is not perfect, just wanted to make sure you know.

**Comment by perak** [comment] 2015-08-02 06:14
As I can see, difference between these two forms is that second one have fields defined. In field list you have only `title` (you don't have fileinput field) so this is not a bug. If you don't have fields defined in a form, then fields are determined from collection.fields. If you have at least one field defined in your form, then generator uses only your_form.fields (it ignores collection.fields). If you add field with `"input": "file" `   into your form.fields then you should see "automagicaly" file upload component.

**Comment by perak** [comment] 2015-08-02 06:26
one more thing not related to this issue: form expects query with `find_one: true` - and will set this property to true automaticaly. this is not directly a problem but if you put query with the same name somewhere else too (not in a form) generator will report error "multiple queries with the same name but different properties". BTW, in next version (0.9.48) queries are significantly changed and file structure is simplified (all queries are defined inside application.queries) an no more code duplication (no more defining the same query in multiple components). No worries - it's backward cokpatible.

**Comment by aaronmyhre** [comment] 2015-08-02 19:12
Hey -

Ok I understand, if you define fields in the form and you want to include the file, then you need to specify it. If you don't define fields, it will just default to what is in collections.fields. Got it, Thanks!

As for 9.48, I am really looking forward to this! Do you have a date you are targeting?

**Comment by perak** [comment] 2015-08-02 20:26
For 0.9.48 - it's ready except I need to create script which converts apps from kitchen-GUI to new format (GUI is not backward compatible) and carefully test the thing. I hope in next 2-3 days.

**Comment by perak** [comment] 2015-08-03 20:24
Closing this issue.

**Closed by perak** 2015-08-03 20:24 UTC
